---
- name: Install collectd and prometheus plugin
  ansible.builtin.package:
    name:
      - "{{ collectd_package_name }}"
      - "{{ collectd_prometheus_plugin }}"
    state: latest

- name: Ensure collectd config directory exists
  ansible.builtin.file:
    path: /etc/collectd.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure write_prometheus plugin
  ansible.builtin.template:
    src: prometheus.conf.j2
    dest: "{{ collectd_prometheus_config_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart collectd

- name: Ensure {{ collectd_service_name }} service is enabled and started
  ansible.builtin.service:
    name: "{{ collectd_service_name }}"
    state: started
    enabled: true

- name: Ensure {{ collectd_prometheus_port }} port is allowed on Firewall
  ansible.posix.firewalld:
    port: "{{ collectd_prometheus_port }}/tcp"
    state: enabled
    permanent: true
    immediate: true