---
- name: Run "Common" role
  hosts: managed_nodes
  become: true
  gather_facts: false
  roles:
    - name: common
      vars:
        disable_selinux: true
        required_packages:
          - curl
          - lsof
          - mc
          - nano
          - tar
          - unzip
          - vim
          - zip